### ISSUE TITLE
Unable to determine if script ran successfully

### ISSUE THREAD

**Issue by admiralmaggie** [sudofox/crowdstrike-recovery-iso#1]
I'm testing this but I'm not able to determine if the script if running properly. Is there a way to make the terminal output stay on screen?

Thank you for writing this BTW

![image](https://github.com/user-attachments/assets/3996c19a-329b-4c5d-82b9-c4afd265c608)

**Comment by sudofox** [comment]
Good catch. I'll make it log to file and also remove the quiet param for boot so that it should boot more verbosely.

**Comment by sudofox** [comment]
might be worth booting to cli instead of gui but eh

**Comment by sudofox** [comment]
I pushed a change up. Try now.

It should log to file in /tmp.

**Comment by sudofox** [comment]
by the way i'm working on building a VM so i can test this stuff myself...im going to have to make a fake driver file lol

**Comment by admiralmaggie** [comment]
Thank you. It's not able to mount. I think the `mkdir` needs to create the iso directory as well.

![image](https://github.com/user-attachments/assets/f1346c5f-e4bf-42d2-8511-297ba7d420d8)

**Comment by sudofox** [comment]
fixed

```
-# Create working directory
-mkdir -p $WORK_DIR
+# Create work dir and also iso dir
+mkdir -p $WORK_DIR/iso
```

idk why it worked for me lol

**Comment by admiralmaggie** [comment]
Awesome! Also, it looks like we need to make `linuxcfg` folder writable:

![image](https://github.com/user-attachments/assets/9c3f1318-af38-4e33-8783-a888f4d2954f)

**Comment by sudofox** [comment]
this is what i get for testing the script while logged in as root

**Comment by admiralmaggie** [comment]
Okay, I got around those and it does create the image. Where should I be able to find `remove_driver.sh` when TC is booted up? I don't see a log file in `/tmp`

![image](https://github.com/user-attachments/assets/166562bf-8e79-4aed-b369-5b5a95e56be0)

**Comment by sudofox** [comment]
That's odd... 

the script can be found at /mnt/sr0/tce/optional/remove_driver.sh

i did some testing and found that tinycorelinux is tiny for a reason: it doesn't have half the utilities i need here (like lsblk). i might have to go back to the drawing board for this thing, honestly.

I still think that it's worthwhile to have a bootable iso because of the sheer number of volumes and pcs that need to have this fixed

**Comment by sudofox** [comment]
maybe tinycoreplus has it, will test

**Comment by admiralmaggie** [comment]
that makes sense. Yeah, what a mess (referring to Crowdstrike). Thanks for sharing your work on this...

**Comment by sudofox** [comment]
Okay, I'm considering using a minimal image of Ubuntu or something instead.

![image](https://github.com/user-attachments/assets/29c2efad-9061-4160-8c7b-e8536bd126c9)

Even if I don't get it solved immediately, I'm sure someone will figure it out for deployment in large environments. I'll keep working on it myself as I have time.

**Comment by sudofox** [comment]
https://github.com/PJ-Singh-001/Cubic

I'm going to try using this next. I would suggest finding another way to fix your hosts for now, since my time is a bit limited (I'm not affected by this issue myself but figured I'd try helping out anyway)

**Comment by admiralmaggie** [comment]
Thank you. Appreciate all your help.
